/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data */
        get: operations["estado_del_bot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bot Status */
        get: operations["estado_de_las_tareas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Bot Start */
        post: operations["post_bot_start_bot_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Bot Stop */
        post: operations["detener_el_bot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kill Switch */
        get: operations["estado_del_corte"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch/engage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Kill Switch Engage
         * @description Corta la apertura de posiciones NUEVAS. Las salidas (stop-loss)
         *     siguen ejecutandose siempre -- ver risk/kill_switch.py.
         */
        post: operations["accionar_el_corte"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Kill Switch Release */
        post: operations["post_kill_switch_release_kill_switch_release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest
         * @description Replay de una estrategia sobre historia real. Sin LLM y sin ordenes.
         */
        get: operations["backtest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Custom Strategies */
        get: operations["listar_estrategias"];
        put?: never;
        /** Post Custom Strategy */
        post: operations["post_custom_strategy_strategies_custom_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/custom/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Custom Strategy */
        delete: operations["delete_custom_strategy_strategies_custom__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Translate Strategy
         * @description Descripcion en castellano -> reglas propuestas. NO guarda nada: lo
         *     que devuelve el modelo es una propuesta para que el usuario la revise
         *     antes de activarla.
         */
        post: operations["post_translate_strategy_strategies_translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market-radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Radar
         * @description Puramente informativo -- ver signals/market_radar.py. No alimenta
         *     ninguna decision de compra.
         */
        get: operations["radar_de_mercado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Asymmetry */
        Asymmetry: {
            /** Target Pct */
            target_pct: number;
            /** Stop Pct */
            stop_pct: number;
            /** Reward Risk */
            reward_risk: number;
            /** Win Prob */
            win_prob: number;
            /** Expected Value Pct */
            expected_value_pct: number;
            /** Volatility Pct */
            volatility_pct: number;
            /** Sample Size */
            sample_size: number;
            /** Resolved Pct */
            resolved_pct: number;
        };
        /** BacktestAnalytics */
        BacktestAnalytics: {
            /** Closed Trades */
            closed_trades: number;
            /** Wins */
            wins?: number | null;
            /** Losses */
            losses?: number | null;
            /** Avg Win Pct */
            avg_win_pct?: number | null;
            /** Avg Loss Pct */
            avg_loss_pct?: number | null;
            /** Best Pct */
            best_pct?: number | null;
            /** Worst Pct */
            worst_pct?: number | null;
            /** Profit Factor */
            profit_factor?: number | null;
            /** Expectancy Pct */
            expectancy_pct?: number | null;
            /** Max Win Streak */
            max_win_streak?: number | null;
            /** Max Loss Streak */
            max_loss_streak?: number | null;
            /** Avg Bars Held */
            avg_bars_held?: number | null;
        };
        /** BacktestBar */
        BacktestBar: {
            /** Time */
            time: number;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
        };
        /** BacktestMetrics */
        BacktestMetrics: {
            /** Closed Trades */
            closed_trades: number;
            /** Total Return Pct */
            total_return_pct: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Win Rate */
            win_rate: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Sortino */
            sortino: number | null;
            /** Calmar */
            calmar: number | null;
        };
        /** BacktestRun */
        BacktestRun: {
            /** Symbol */
            symbol: string;
            /** Strategy */
            strategy: string;
            /** Period */
            period: string;
            metrics: components["schemas"]["BacktestMetrics"];
            analytics: components["schemas"]["BacktestAnalytics"];
            /** Equity Curve */
            equity_curve: number[];
            /** Bars */
            bars: components["schemas"]["BacktestBar"][];
            /** Trades */
            trades: components["schemas"]["BacktestTradeRow"][];
            /** Available Strategies */
            available_strategies: string[];
        };
        /** BacktestTradeRow */
        BacktestTradeRow: {
            /** Entry Time */
            entry_time: number | null;
            /** Entry Price */
            entry_price: number;
            /** Exit Time */
            exit_time: number | null;
            /** Exit Price */
            exit_price: number | null;
            /** Exit Reason */
            exit_reason: string | null;
            /** Pnl Pct */
            pnl_pct: number | null;
        };
        /** Breaker */
        Breaker: {
            /** Date */
            date: string;
            /** Day Start Value */
            day_start_value: number;
            /** Consecutive Losses */
            consecutive_losses: number;
            /** Halted */
            halted: boolean;
            /** Halt Reason */
            halt_reason: string | null;
        };
        /** ClosedTrade */
        ClosedTrade: {
            /** Pool */
            pool: string;
            /** Symbol */
            symbol: string;
            /** Exit Price */
            exit_price: number | null;
            /** Stop */
            stop: number | null;
            /** Won */
            won: boolean | null;
            /** Closed At */
            closed_at: string;
            /** Opened At */
            opened_at: string | null;
            /** Bucket */
            bucket: string | null;
            /** Position Usd */
            position_usd: number | null;
            /** Reasoning */
            reasoning: string | null;
        };
        /** CustomStrategy */
        CustomStrategy: {
            /** Name */
            name: string;
            /** Entry */
            entry: components["schemas"]["StrategyRule"][];
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** CustomStrategyList */
        CustomStrategyList: {
            /** Strategies */
            strategies: components["schemas"]["CustomStrategy"][];
            /** Available Indicators */
            available_indicators: string[];
            /** Available Operators */
            available_operators: string[];
        };
        /** DashboardData */
        DashboardData: {
            /** Generated At */
            generated_at: string;
            /** Pools */
            pools: {
                [key: string]: components["schemas"]["PoolHealth"];
            };
            /** Positions */
            positions: {
                [key: string]: {
                    [key: string]: components["schemas"]["Position"];
                };
            };
            /** Live Positions */
            live_positions: components["schemas"]["LivePosition"][];
            /** Breakers */
            breakers: {
                [key: string]: components["schemas"]["Breaker"];
            };
            /** Spend */
            spend: {
                [key: string]: components["schemas"]["Spend"];
            };
            /** Standings */
            standings: components["schemas"]["Standing"][];
            /** Strategy Performance */
            strategy_performance: components["schemas"]["StrategyPerformance"][];
            watchlist: components["schemas"]["WatchlistStatus"];
            /** Last Scan */
            last_scan: {
                [key: string]: unknown;
            } | null;
            panel_sentiment: components["schemas"]["PanelSentiment"] | null;
            /** Discovery */
            discovery: {
                [key: string]: {
                    [key: string]: unknown;
                } | null;
            };
            /** Rejection Totals */
            rejection_totals: {
                [key: string]: number;
            };
            /** Deployment Alerts */
            deployment_alerts: {
                [key: string]: components["schemas"]["DeploymentAlert"];
            };
            portfolio: components["schemas"]["Portfolio"];
            /** Portfolio Series */
            portfolio_series: components["schemas"]["PortfolioPoint"][];
            performance: components["schemas"]["Performance"];
            risk: components["schemas"]["RiskCenter"];
            /** Closed Trades */
            closed_trades: components["schemas"]["ClosedTrade"][];
            /** Error Count */
            error_count: number;
            /** Last Error */
            last_error: {
                [key: string]: unknown;
            } | null;
            /** Recent Decisions */
            recent_decisions: {
                [key: string]: unknown;
            }[];
            /** Recent Trades */
            recent_trades: {
                [key: string]: unknown;
            }[];
            /** Sparklines */
            sparklines: {
                [key: string]: number[];
            };
        };
        /** DeploymentAlert */
        DeploymentAlert: {
            /** Timestamp */
            timestamp: string;
            /** Age Minutes */
            age_minutes: number;
            /** Diagnosis */
            diagnosis: string | null;
            /** Detail */
            detail: string | null;
            /** Assets Scanned */
            assets_scanned: number | null;
            /** Shortlisted */
            shortlisted: number | null;
        };
        /** DexMover */
        DexMover: {
            /** Symbol */
            symbol: string;
            /** Exchange */
            exchange: string;
            /** Price */
            price: number;
            /** Change 24H Pct */
            change_24h_pct: number;
            /** Volume 24H Usd */
            volume_24h_usd: number;
            /** Suspicious */
            suspicious: boolean;
            /** Blockchain */
            blockchain: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KillSwitchRequest */
        KillSwitchRequest: {
            /** Reason */
            reason?: string | null;
            /** Pools */
            pools?: string[] | null;
        };
        /**
         * KillSwitchStatus
         * @description None = ese pool puede abrir posiciones; string = motivo del corte.
         */
        KillSwitchStatus: {
            /** Stocks Blocked */
            stocks_blocked: string | null;
            /** Crypto Blocked */
            crypto_blocked: string | null;
        };
        /** LargestPosition */
        LargestPosition: {
            /** Symbol */
            symbol: string;
            /** Pool */
            pool: string;
            /** Market Value */
            market_value: number;
        };
        /** LivePosition */
        LivePosition: {
            /** Pool */
            pool: string;
            /** Symbol */
            symbol: string;
            /** Entry Price */
            entry_price: number;
            /** Current Price */
            current_price: number | null;
            /** Qty */
            qty: number;
            /** Stop */
            stop: number;
            /** Market Value */
            market_value: number;
            /** Pnl Usd */
            pnl_usd: number | null;
            /** Pnl Pct */
            pnl_pct: number | null;
            /** Risk Usd */
            risk_usd: number;
            /** Opened At */
            opened_at: string | null;
            /** Strategy */
            strategy: string | null;
            /** Bucket */
            bucket: string | null;
            /** Confidence */
            confidence: number | null;
            /** Reasoning */
            reasoning: string | null;
            asymmetry: components["schemas"]["Asymmetry"] | null;
            /** Opportunity Score */
            opportunity_score: number | null;
        };
        /** MarketRadar */
        MarketRadar: {
            /** Generated At */
            generated_at: string;
            /** Cex Movers */
            cex_movers: components["schemas"]["Mover"][];
            /** Dex Movers */
            dex_movers: components["schemas"]["DexMover"][];
        };
        /** Mover */
        Mover: {
            /** Symbol */
            symbol: string;
            /** Exchange */
            exchange: string;
            /** Price */
            price: number;
            /** Change 24H Pct */
            change_24h_pct: number;
            /** Volume 24H Usd */
            volume_24h_usd: number;
            /** Suspicious */
            suspicious: boolean;
        };
        /** PanelSentiment */
        PanelSentiment: {
            /** Buy Pct */
            buy_pct: number;
            /** Sample */
            sample: number;
        };
        /** Performance */
        Performance: {
            /** Available */
            available: boolean;
            /** Points */
            points: number;
            /** Reason */
            reason?: string | null;
            /** Total Return Pct */
            total_return_pct?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Volatility Pct */
            volatility_pct?: number | null;
        };
        /** PoolHealth */
        PoolHealth: {
            /** Last Result */
            last_result: string | null;
            /** Last Timestamp */
            last_timestamp: string | null;
            /** Age Minutes */
            age_minutes: number | null;
            /** Stale */
            stale: boolean;
        };
        /** Portfolio */
        Portfolio: {
            /** Total Capital */
            total_capital: number | null;
            /** Deployed Capital */
            deployed_capital: number;
            /** Cash Pct */
            cash_pct: number | null;
            /** N Positions */
            n_positions: number;
            /** Buckets */
            buckets: {
                [key: string]: number;
            };
        };
        /** PortfolioPoint */
        PortfolioPoint: {
            /** Timestamp */
            timestamp: string;
            /** Total Value */
            total_value: number;
        };
        /** Position */
        Position: {
            /** Entry Price */
            entry_price: number;
            /** Qty */
            qty: number;
            /** Stop */
            stop: number;
        };
        /** RiskAlert */
        RiskAlert: {
            /** Level */
            level: string;
            /** Code */
            code: string;
            /** Detail */
            detail: string;
        };
        /** RiskCenter */
        RiskCenter: {
            /** Total Capital */
            total_capital: number | null;
            /** Exposure Pct */
            exposure_pct: number | null;
            /** Exposure By Pool */
            exposure_by_pool: {
                [key: string]: number;
            };
            /** Bucket Exposure */
            bucket_exposure: {
                [key: string]: number;
            };
            /** Open Risk Usd */
            open_risk_usd: number;
            largest_position: components["schemas"]["LargestPosition"] | null;
            /** N Positions */
            n_positions: number;
            /** Max Open Positions */
            max_open_positions: number;
            /** Max Deployed Pct */
            max_deployed_pct: number;
            /** Spend Today */
            spend_today: {
                [key: string]: components["schemas"]["Spend"];
            };
            /** Alerts */
            alerts: components["schemas"]["RiskAlert"][];
        };
        /** Spend */
        Spend: {
            /** Date */
            date: string;
            /** Spent */
            spent: number;
        };
        /** Standing */
        Standing: {
            /** Strategy */
            strategy: string;
            /** Scored */
            scored: number;
            /** Open Proposals */
            open_proposals: number;
            /** Win Rate */
            win_rate: number | null;
            /** Avg Return Pct */
            avg_return_pct: number | null;
            /** Best Pct */
            best_pct: number | null;
            /** Worst Pct */
            worst_pct: number | null;
        };
        /** StrategyPerformance */
        StrategyPerformance: {
            /** Strategy */
            strategy: string;
            /** Scored */
            scored: number;
            /** Open Proposals */
            open_proposals: number;
            /** Win Rate */
            win_rate: number | null;
            /** Avg Return Pct */
            avg_return_pct: number | null;
            /** Best Pct */
            best_pct: number | null;
            /** Worst Pct */
            worst_pct: number | null;
            /** Status */
            status: string;
        };
        /** StrategyRule */
        StrategyRule: {
            /** Indicator */
            indicator: string;
            /** Op */
            op: string;
            /** Value */
            value: number | string | boolean;
        };
        /** TaskStatusResponse */
        TaskStatusResponse: {
            /** Tasks */
            tasks: {
                [key: string]: string;
            };
        };
        /** TranslateRequest */
        TranslateRequest: {
            /** Description */
            description: string;
        };
        /** TranslatedStrategy */
        TranslatedStrategy: {
            /** Entry */
            entry: components["schemas"]["StrategyRule"][];
            /** Resumen */
            resumen: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistEntry */
        WatchlistEntry: {
            /** Symbol */
            symbol: string;
            /** Change Pct */
            change_pct: number;
            /** Rsi 14 */
            rsi_14: number;
            /** Sma Trend */
            sma_trend: string;
            /** Insider Net Usd */
            insider_net_usd: number;
            /** Analyst Upside Pct */
            analyst_upside_pct: number | null;
            /** Score */
            score: number;
        };
        /** WatchlistStatus */
        WatchlistStatus: {
            /** Symbols */
            symbols: string[];
            /** Detail */
            detail: components["schemas"]["WatchlistEntry"][];
            /** Last Updated */
            last_updated: string | null;
            /** Age Minutes */
            age_minutes: number | null;
            /** Stale */
            stale: boolean;
            /** Last Error */
            last_error: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    estado_del_bot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardData"];
                };
            };
        };
    };
    estado_de_las_tareas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
    post_bot_start_bot_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
    detener_el_bot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
    estado_del_corte: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchStatus"];
                };
            };
        };
    };
    accionar_el_corte: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KillSwitchRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_kill_switch_release_kill_switch_release_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchStatus"];
                };
            };
        };
    };
    backtest: {
        parameters: {
            query?: {
                symbol?: string;
                strategy?: string;
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_estrategias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomStrategyList"];
                };
            };
        };
    };
    post_custom_strategy_strategies_custom_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomStrategy"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomStrategyList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_custom_strategy_strategies_custom__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomStrategyList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_translate_strategy_strategies_translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslatedStrategy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radar_de_mercado: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketRadar"];
                };
            };
        };
    };
}
