/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data */
        get: operations["get_data_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bot Status */
        get: operations["get_bot_status_bot_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Bot Start */
        post: operations["post_bot_start_bot_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bot-stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Bot Stop */
        post: operations["post_bot_stop_bot_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Asymmetry */
        Asymmetry: {
            /** Target Pct */
            target_pct: number;
            /** Stop Pct */
            stop_pct: number;
            /** Reward Risk */
            reward_risk: number;
            /** Win Prob */
            win_prob: number;
            /** Expected Value Pct */
            expected_value_pct: number;
            /** Volatility Pct */
            volatility_pct: number;
            /** Sample Size */
            sample_size: number;
            /** Resolved Pct */
            resolved_pct: number;
        };
        /** Breaker */
        Breaker: {
            /** Date */
            date: string;
            /** Day Start Value */
            day_start_value: number;
            /** Consecutive Losses */
            consecutive_losses: number;
            /** Halted */
            halted: boolean;
            /** Halt Reason */
            halt_reason: string | null;
        };
        /** ClosedTrade */
        ClosedTrade: {
            /** Pool */
            pool: string;
            /** Symbol */
            symbol: string;
            /** Exit Price */
            exit_price: number | null;
            /** Stop */
            stop: number | null;
            /** Won */
            won: boolean | null;
            /** Closed At */
            closed_at: string;
            /** Opened At */
            opened_at: string | null;
            /** Bucket */
            bucket: string | null;
            /** Position Usd */
            position_usd: number | null;
            /** Reasoning */
            reasoning: string | null;
        };
        /** DashboardData */
        DashboardData: {
            /** Generated At */
            generated_at: string;
            /** Pools */
            pools: {
                [key: string]: components["schemas"]["PoolHealth"];
            };
            /** Positions */
            positions: {
                [key: string]: {
                    [key: string]: components["schemas"]["Position"];
                };
            };
            /** Live Positions */
            live_positions: components["schemas"]["LivePosition"][];
            /** Breakers */
            breakers: {
                [key: string]: components["schemas"]["Breaker"];
            };
            /** Spend */
            spend: {
                [key: string]: components["schemas"]["Spend"];
            };
            /** Standings */
            standings: components["schemas"]["Standing"][];
            /** Strategy Performance */
            strategy_performance: components["schemas"]["StrategyPerformance"][];
            watchlist: components["schemas"]["WatchlistStatus"];
            /** Last Scan */
            last_scan: {
                [key: string]: unknown;
            } | null;
            panel_sentiment: components["schemas"]["PanelSentiment"] | null;
            /** Discovery */
            discovery: {
                [key: string]: {
                    [key: string]: unknown;
                } | null;
            };
            /** Rejection Totals */
            rejection_totals: {
                [key: string]: number;
            };
            /** Deployment Alerts */
            deployment_alerts: {
                [key: string]: components["schemas"]["DeploymentAlert"];
            };
            portfolio: components["schemas"]["Portfolio"];
            /** Portfolio Series */
            portfolio_series: components["schemas"]["PortfolioPoint"][];
            performance: components["schemas"]["Performance"];
            risk: components["schemas"]["RiskCenter"];
            /** Closed Trades */
            closed_trades: components["schemas"]["ClosedTrade"][];
            /** Error Count */
            error_count: number;
            /** Last Error */
            last_error: {
                [key: string]: unknown;
            } | null;
            /** Recent Decisions */
            recent_decisions: {
                [key: string]: unknown;
            }[];
            /** Recent Trades */
            recent_trades: {
                [key: string]: unknown;
            }[];
        };
        /** DeploymentAlert */
        DeploymentAlert: {
            /** Timestamp */
            timestamp: string;
            /** Age Minutes */
            age_minutes: number;
            /** Diagnosis */
            diagnosis: string | null;
            /** Detail */
            detail: string | null;
            /** Assets Scanned */
            assets_scanned: number | null;
            /** Shortlisted */
            shortlisted: number | null;
        };
        /** LargestPosition */
        LargestPosition: {
            /** Symbol */
            symbol: string;
            /** Pool */
            pool: string;
            /** Market Value */
            market_value: number;
        };
        /** LivePosition */
        LivePosition: {
            /** Pool */
            pool: string;
            /** Symbol */
            symbol: string;
            /** Entry Price */
            entry_price: number;
            /** Current Price */
            current_price: number | null;
            /** Qty */
            qty: number;
            /** Stop */
            stop: number;
            /** Market Value */
            market_value: number;
            /** Pnl Usd */
            pnl_usd: number | null;
            /** Pnl Pct */
            pnl_pct: number | null;
            /** Risk Usd */
            risk_usd: number;
            /** Opened At */
            opened_at: string | null;
            /** Strategy */
            strategy: string | null;
            /** Bucket */
            bucket: string | null;
            /** Confidence */
            confidence: number | null;
            /** Reasoning */
            reasoning: string | null;
            asymmetry: components["schemas"]["Asymmetry"] | null;
            /** Opportunity Score */
            opportunity_score: number | null;
        };
        /** PanelSentiment */
        PanelSentiment: {
            /** Buy Pct */
            buy_pct: number;
            /** Sample */
            sample: number;
        };
        /** Performance */
        Performance: {
            /** Available */
            available: boolean;
            /** Points */
            points: number;
            /** Reason */
            reason?: string | null;
            /** Total Return Pct */
            total_return_pct?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Volatility Pct */
            volatility_pct?: number | null;
        };
        /** PoolHealth */
        PoolHealth: {
            /** Last Result */
            last_result: string | null;
            /** Last Timestamp */
            last_timestamp: string | null;
            /** Age Minutes */
            age_minutes: number | null;
            /** Stale */
            stale: boolean;
        };
        /** Portfolio */
        Portfolio: {
            /** Total Capital */
            total_capital: number | null;
            /** Deployed Capital */
            deployed_capital: number;
            /** Cash Pct */
            cash_pct: number | null;
            /** N Positions */
            n_positions: number;
            /** Buckets */
            buckets: {
                [key: string]: number;
            };
        };
        /** PortfolioPoint */
        PortfolioPoint: {
            /** Timestamp */
            timestamp: string;
            /** Total Value */
            total_value: number;
        };
        /** Position */
        Position: {
            /** Entry Price */
            entry_price: number;
            /** Qty */
            qty: number;
            /** Stop */
            stop: number;
        };
        /** RiskAlert */
        RiskAlert: {
            /** Level */
            level: string;
            /** Code */
            code: string;
            /** Detail */
            detail: string;
        };
        /** RiskCenter */
        RiskCenter: {
            /** Total Capital */
            total_capital: number | null;
            /** Exposure Pct */
            exposure_pct: number | null;
            /** Exposure By Pool */
            exposure_by_pool: {
                [key: string]: number;
            };
            /** Bucket Exposure */
            bucket_exposure: {
                [key: string]: number;
            };
            /** Open Risk Usd */
            open_risk_usd: number;
            largest_position: components["schemas"]["LargestPosition"] | null;
            /** N Positions */
            n_positions: number;
            /** Max Open Positions */
            max_open_positions: number;
            /** Max Deployed Pct */
            max_deployed_pct: number;
            /** Spend Today */
            spend_today: {
                [key: string]: components["schemas"]["Spend"];
            };
            /** Alerts */
            alerts: components["schemas"]["RiskAlert"][];
        };
        /** Spend */
        Spend: {
            /** Date */
            date: string;
            /** Spent */
            spent: number;
        };
        /** Standing */
        Standing: {
            /** Strategy */
            strategy: string;
            /** Scored */
            scored: number;
            /** Open Proposals */
            open_proposals: number;
            /** Win Rate */
            win_rate: number | null;
            /** Avg Return Pct */
            avg_return_pct: number | null;
            /** Best Pct */
            best_pct: number | null;
            /** Worst Pct */
            worst_pct: number | null;
        };
        /** StrategyPerformance */
        StrategyPerformance: {
            /** Strategy */
            strategy: string;
            /** Scored */
            scored: number;
            /** Open Proposals */
            open_proposals: number;
            /** Win Rate */
            win_rate: number | null;
            /** Avg Return Pct */
            avg_return_pct: number | null;
            /** Best Pct */
            best_pct: number | null;
            /** Worst Pct */
            worst_pct: number | null;
            /** Status */
            status: string;
        };
        /** TaskStatusResponse */
        TaskStatusResponse: {
            /** Tasks */
            tasks: {
                [key: string]: string;
            };
        };
        /** WatchlistEntry */
        WatchlistEntry: {
            /** Symbol */
            symbol: string;
            /** Change Pct */
            change_pct: number;
            /** Rsi 14 */
            rsi_14: number;
            /** Sma Trend */
            sma_trend: string;
            /** Insider Net Usd */
            insider_net_usd: number;
            /** Analyst Upside Pct */
            analyst_upside_pct: number | null;
            /** Score */
            score: number;
        };
        /** WatchlistStatus */
        WatchlistStatus: {
            /** Symbols */
            symbols: string[];
            /** Detail */
            detail: components["schemas"]["WatchlistEntry"][];
            /** Last Updated */
            last_updated: string | null;
            /** Age Minutes */
            age_minutes: number | null;
            /** Stale */
            stale: boolean;
            /** Last Error */
            last_error: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_data_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardData"];
                };
            };
        };
    };
    get_bot_status_bot_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
    post_bot_start_bot_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
    post_bot_stop_bot_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
        };
    };
}
